version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_server
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch_server
    ports:
      - "9200:9200"
    volumes:
        - es_data:/user/share/elasticsearch/data
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m


  node_api:
    build: ./backend/node
    container_name: node_app
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - rabbitmq
      - elasticsearch
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RABBIT_URL=amqp://admin:admin@rabbitmq:5672//
      - ELASTIC_URL=http://elasticsearch:9200
    restart: always

  fastapi:
    build:
      context: ./backend/python
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - rabbitmq
      - elasticsearch
      - node_api
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RABBIT_URL=amqp://admin:admin@rabbitmq:5672//
      - ELASTIC_URL=http://elasticsearch:9200
      - NODE_SCRAPER_URL=http://node_api:5000
      - DATABASE_URL="postgresql://postgres.sfdzwhjgegdtlndsepxs:MarketHubPS853@aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require"
    restart: always

volumes:
  redis_data:
  rabbitmq_data:
  es_data:
