FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Make sure Celery can import tasks correctly
ENV PYTHONPATH=/app

# Start the celery worker
CMD ["celery", "-A", "tasks.analyze_tasks", "worker", "--loglevel=info", "-Q", "analysis"]
